### ISSUE TITLE
Plugin Broken at Yarn v3.0.0-rc.10 and Higher

### ISSUE THREAD

**Issue by Kurt-von-Laven** [tophat/yarn-plugin-licenses#16]
**Describe the bug**

The plugin works on Yarn v3.0.0-rc.1 through Yarn v3.0.0-rc.9. It does not support Yarn v2 or lower, but there is already an open feature request (#14) for that. 

**To reproduce**

1. Run `yarn set version v3.0.0` (or use any release candidate above 9).
2. Run the license auditor plugin.
3. The plugin crashes with the following error message: `TypeError: e.miscUtils.dynamicRequireNoCache is not a function`. No output XML file is generated.

**Expected behavior**

The plugin runs successfully, producing the output XML file.

**Environment (please complete the following information):**

- OS: Ubuntu 21.04
- Plugin Version: c2abd459501318dded85841a748bc513b49b3b11
- Node Version: v16.5.0

**Comment by noahnu** [comment]
It should be fixed now. Please let me know.

**Comment by Kurt-von-Laven** [comment]
Yes, that fixed it at Yarn v3.0.0; thank you!
